CPP=g++
CPPFLAGS=-Wall -g

all:
	$(CPP) queue.hpp linkQueue.hpp doubleStackQueue.hpp initQueue.hpp linkQueueImplement.cpp queueImplement.cpp doubleStackQueueImplement.cpp useQueue.cpp -o useQueue.exe
clean:
	rm *.exe